### ISSUE TITLE
Example of the README.md does not work

### ISSUE THREAD

**Issue by christiankral** [KronosTheLate/CircuitComponentRounding.jl#4]
The example

```julia
determine_E(220, 470, 680)
```

shown in the README.md does not work with v0.3.1. Instead the following works:

```julia
CircuitComponentRounding.determine_E(220, 470, 680)
``` 

So either the documentation needs to be fixed to the function `determine_E` needs to be accessible directly.

**Comment by KronosTheLate** [comment]
Exported `determine_E` in https://github.com/KronosTheLate/CircuitComponentRounding.jl/commit/d98a9f5d8c0781ffa0fb16cf2622fdbb80fda915#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26.

Thanks a lot for your input!
